import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "DreamAI",
  description: "Generated by Md. Sajal Ali",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main>{children}</main>
    </>
  );
}
